
// Primitive Data Type

Integer a = 10;
Integer b;


// S Object Data Type

Account acc = new Account();

// Create Object.

Account acc = new Account(Name='Test', BillingCity='Jaipur', Phone='12345687');

// Another Method.

Account acc = new Account();

acc.Name = 'Test';
acc.Phone = '123456789';
acc.Rating = 'Hot';
acc.Fax = '123456';
acc.Industry = 'Energy';
Inset acc;